// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA04vu-9UFnhxsgUwCDWcgSnJWze0UJfDI',
    appId: '1:977586964405:web:642333f256e97d6780fbfc',
    messagingSenderId: '977586964405',
    projectId: 'mobilechat-b1c7f',
    authDomain: 'mobilechat-b1c7f.firebaseapp.com',
    databaseURL: 'https://mobilechat-b1c7f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilechat-b1c7f.firebasestorage.app',
    measurementId: 'G-WLJPMJDLZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHhn_21M13IvNlGpl_YxabBbFVbohcMI',
    appId: '1:977586964405:android:e9851207689350d780fbfc',
    messagingSenderId: '977586964405',
    projectId: 'mobilechat-b1c7f',
    databaseURL: 'https://mobilechat-b1c7f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilechat-b1c7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArS6w3p0Dsq0Pfu_YEQisTEkoY2jbD7hY',
    appId: '1:977586964405:ios:22199ad79122eda980fbfc',
    messagingSenderId: '977586964405',
    projectId: 'mobilechat-b1c7f',
    databaseURL: 'https://mobilechat-b1c7f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilechat-b1c7f.firebasestorage.app',
    iosClientId: '977586964405-9j90amtgraaienbutus9fd1h9n6hf884.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArS6w3p0Dsq0Pfu_YEQisTEkoY2jbD7hY',
    appId: '1:977586964405:ios:22199ad79122eda980fbfc',
    messagingSenderId: '977586964405',
    projectId: 'mobilechat-b1c7f',
    databaseURL: 'https://mobilechat-b1c7f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilechat-b1c7f.firebasestorage.app',
    iosClientId: '977586964405-9j90amtgraaienbutus9fd1h9n6hf884.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA04vu-9UFnhxsgUwCDWcgSnJWze0UJfDI',
    appId: '1:977586964405:web:9bed67459eb94d9b80fbfc',
    messagingSenderId: '977586964405',
    projectId: 'mobilechat-b1c7f',
    authDomain: 'mobilechat-b1c7f.firebaseapp.com',
    databaseURL: 'https://mobilechat-b1c7f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilechat-b1c7f.firebasestorage.app',
    measurementId: 'G-K2P6NKELQY',
  );
}
